# Generated by Django 4.2.9 on 2024-04-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.TextField(max_length=200)),
                ('recipe_category', models.TextField(max_length=200)),
            ],
        ),
    ]
